#pragma once

#define BCAT_ORTHO_LAYERS

#define SPLIT_ACTIVITY_ENABLE
#define SPLIT_HAND_PIN B4
#define SPLIT_HAND_PIN_LOW_IS_LEFT
#define SPLIT_OLED_ENABLE
#define SPLIT_USB_DETECT
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WPM_ENABLE
#define TAPPING_TERM 200

#define OLED_BRIGHTNESS 25
